apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: tdh-postgres-singleton
spec:
  memory: 800Mi
  cpu: "0.4"
  storageClassName: standard
  storageSize: 10G
  pgConfig:
     dbname: tdh-postgres-db
     username: pgadmin
  serviceType: LoadBalancer
  highAvailability:
     enabled: false
  backupLocationSecret:
     name: s3-secret-postgres
