apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: tdh-postgres-ha
spec:
  memory: XXX_MEM_XXX
  cpu: "XXX_CPU_XXX"
  storageClassName: standard
  storageSize: XXX_DISK_XXX
  serviceType: LoadBalancer
  pgConfig:
    dbname: tdh-postgres-db
    username: pgadmin
  highAvailability:
    enabled: true
  backupLocationSecret:
    name: s3-secret-postgres
