---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: https-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - secretName: https-secret
    hosts:
      - echoserver.DOMAIN
      - echoserver1.DOMAIN
      - echoserver2.DOMAIN
  rules:
  - host: echoserver.DOMAIN
    http:
      paths:
      - backend:
          serviceName: echoserver-1
          servicePort: 8080
  - host: stilton-cheese.DOMAIN
    http:
      paths:
      - backend:
          serviceName: echoserver-2
          servicePort: 8080
