apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fortune-ingress
  namespace: NAMESPACE
  annotations:
    kubernetes.io/ingress.class: contour
  labels:
    app: fortune-app
spec:
  tls:
  - hosts:
    - fortune.DNS_DOMAIN
    secretName: https-secret
  rules:
  - host: fortune.DNS_DOMAIN
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fortune-service
            port:
              number: 80
