---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fortune-ingress
  namespace: NAMESPACE
  labels:
    app: fortune-app
spec:
  tls:
  - secretName: https-secret
    hosts:
      - fortune.DNS_DOMAIN
  rules:
  - host: fortune.DNS_DOMAIN
    http:
      paths:
      - path: /
        backend:
          serviceName: fortune-service
          servicePort: 80
